// Generated by https://github.com/juliettef/IconFontCppHeaders script GenerateIconFontCppHeaders.py
// for languages C and C++ from
// https://raw.githubusercontent.com/FortAwesome/Font-Awesome/master/metadata/icons.yml for use with
// https://github.com/FortAwesome/Font-Awesome/blob/master/webfonts/fa-solid-900.ttf
#pragma once

#include "obfuscate/obfuscate.h"

#define FONT_ICON_FILE_NAME_FAR OBF("fa-regular-400.ttf")
#define FONT_ICON_FILE_NAME_FAS OBF("fa-solid-900.ttf")

#define ICON_MIN_FA 0xf000
#define ICON_MAX_FA 0xf942

#define ICON_FA_USER OBF("\uf007")
#define ICON_FA_LOCK OBF("\uf023")
#define ICON_FA_EYE OBF("\uf06e")
#define ICON_FA_EYE_SLASH OBF("\uf070")
#define ICON_FA_TIMES OBF("\uf00d")
#define ICON_FA_MINUS OBF("\uf068")
#define ICON_FA_CHECK OBF("\uf00c")
#define ICON_FA_EXCLAMATION_TRIANGLE OBF("\uf071")
#define ICON_FA_KEY OBF("\uf084")
